//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.1378
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VUTPP {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandBar() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VUTPP.CommandBar", typeof(CommandBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Aktion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deAction {
            get {
                return ResourceManager.GetString("deAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add-Ins과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deAddins {
            get {
                return ResourceManager.GetString("deAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erstellen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deBuild {
            get {
                return ResourceManager.GetString("deBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Klassendiagramm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deClass_Diagram {
            get {
                return ResourceManager.GetString("deClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Community과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deCommunity {
            get {
                return ResourceManager.GetString("deCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daten과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deData {
            get {
                return ResourceManager.GetString("deData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Datenbank과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deDatabase {
            get {
                return ResourceManager.GetString("deDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Datenbankdiagramm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deDatabase_Diagram {
            get {
                return ResourceManager.GetString("deDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debuggen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deDebug {
            get {
                return ResourceManager.GetString("deDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagramm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deDiagram {
            get {
                return ResourceManager.GetString("deDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bearbeiten과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deEdit {
            get {
                return ResourceManager.GetString("deEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Datei과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deFile {
            get {
                return ResourceManager.GetString("deFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deFormat {
            get {
                return ResourceManager.GetString("deFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rahmen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deFrames {
            get {
                return ResourceManager.GetString("deFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hilfe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deHelp {
            get {
                return ResourceManager.GetString("deHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bild과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deImage {
            get {
                return ResourceManager.GetString("deImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deLayout {
            get {
                return ResourceManager.GetString("deLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makros과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deMacros {
            get {
                return ResourceManager.GetString("deMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projekt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deProject {
            get {
                return ResourceManager.GetString("deProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deQuery {
            get {
                return ResourceManager.GetString("deQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abfrage-Designer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deQuery_Designer {
            get {
                return ResourceManager.GetString("deQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Umgestalten과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deRefactor {
            get {
                return ResourceManager.GetString("deRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ressourcen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deResources {
            get {
                return ResourceManager.GetString("deResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schema과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deSchema {
            get {
                return ResourceManager.GetString("deSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deStyles {
            get {
                return ResourceManager.GetString("deStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabelle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deTable {
            get {
                return ResourceManager.GetString("deTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabellen-Designer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deTable_Designer {
            get {
                return ResourceManager.GetString("deTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deTeam {
            get {
                return ResourceManager.GetString("deTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Testen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deTest {
            get {
                return ResourceManager.GetString("deTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extras과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deTools {
            get {
                return ResourceManager.GetString("deTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ansicht과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deView {
            get {
                return ResourceManager.GetString("deView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fenster과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deWindow {
            get {
                return ResourceManager.GetString("deWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deXML {
            get {
                return ResourceManager.GetString("deXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enAction {
            get {
                return ResourceManager.GetString("enAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Addins과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enAddins {
            get {
                return ResourceManager.GetString("enAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enBuild {
            get {
                return ResourceManager.GetString("enBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Class Diagram과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enClass_Diagram {
            get {
                return ResourceManager.GetString("enClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Community과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enCommunity {
            get {
                return ResourceManager.GetString("enCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enData {
            get {
                return ResourceManager.GetString("enData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enDatabase {
            get {
                return ResourceManager.GetString("enDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database Diagram과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enDatabase_Diagram {
            get {
                return ResourceManager.GetString("enDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enDebug {
            get {
                return ResourceManager.GetString("enDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagram과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enDiagram {
            get {
                return ResourceManager.GetString("enDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enEdit {
            get {
                return ResourceManager.GetString("enEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enFile {
            get {
                return ResourceManager.GetString("enFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enFormat {
            get {
                return ResourceManager.GetString("enFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frames과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enFrames {
            get {
                return ResourceManager.GetString("enFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enHelp {
            get {
                return ResourceManager.GetString("enHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enImage {
            get {
                return ResourceManager.GetString("enImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enLayout {
            get {
                return ResourceManager.GetString("enLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macros과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enMacros {
            get {
                return ResourceManager.GetString("enMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enProject {
            get {
                return ResourceManager.GetString("enProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enQuery {
            get {
                return ResourceManager.GetString("enQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query Designer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enQuery_Designer {
            get {
                return ResourceManager.GetString("enQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refactor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enRefactor {
            get {
                return ResourceManager.GetString("enRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resources과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enResources {
            get {
                return ResourceManager.GetString("enResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schema과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enSchema {
            get {
                return ResourceManager.GetString("enSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Styles과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enStyles {
            get {
                return ResourceManager.GetString("enStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enTable {
            get {
                return ResourceManager.GetString("enTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table Designer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enTable_Designer {
            get {
                return ResourceManager.GetString("enTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enTeam {
            get {
                return ResourceManager.GetString("enTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enTest {
            get {
                return ResourceManager.GetString("enTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enTools {
            get {
                return ResourceManager.GetString("enTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enView {
            get {
                return ResourceManager.GetString("enView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enWindow {
            get {
                return ResourceManager.GetString("enWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enXML {
            get {
                return ResourceManager.GetString("enXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acción과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esAction {
            get {
                return ResourceManager.GetString("esAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complementos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esAddins {
            get {
                return ResourceManager.GetString("esAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esBuild {
            get {
                return ResourceManager.GetString("esBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagrama de clase과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esClass_Diagram {
            get {
                return ResourceManager.GetString("esClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comunidad과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esCommunity {
            get {
                return ResourceManager.GetString("esCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Datos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esData {
            get {
                return ResourceManager.GetString("esData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base de datos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esDatabase {
            get {
                return ResourceManager.GetString("esDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagrama de base de datos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esDatabase_Diagram {
            get {
                return ResourceManager.GetString("esDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Depurar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esDebug {
            get {
                return ResourceManager.GetString("esDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagrama과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esDiagram {
            get {
                return ResourceManager.GetString("esDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esEdit {
            get {
                return ResourceManager.GetString("esEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archivo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esFile {
            get {
                return ResourceManager.GetString("esFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formato과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esFormat {
            get {
                return ResourceManager.GetString("esFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marcos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esFrames {
            get {
                return ResourceManager.GetString("esFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayuda과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esHelp {
            get {
                return ResourceManager.GetString("esHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imagen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esImage {
            get {
                return ResourceManager.GetString("esImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diseño과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esLayout {
            get {
                return ResourceManager.GetString("esLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macros과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esMacros {
            get {
                return ResourceManager.GetString("esMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proyecto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esProject {
            get {
                return ResourceManager.GetString("esProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esQuery {
            get {
                return ResourceManager.GetString("esQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diseñador de consultas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esQuery_Designer {
            get {
                return ResourceManager.GetString("esQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refactorizar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esRefactor {
            get {
                return ResourceManager.GetString("esRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recursos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esResources {
            get {
                return ResourceManager.GetString("esResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Esquema과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esSchema {
            get {
                return ResourceManager.GetString("esSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Estilos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esStyles {
            get {
                return ResourceManager.GetString("esStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabla과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esTable {
            get {
                return ResourceManager.GetString("esTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diseñador de tablas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esTable_Designer {
            get {
                return ResourceManager.GetString("esTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esTeam {
            get {
                return ResourceManager.GetString("esTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prueba과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esTest {
            get {
                return ResourceManager.GetString("esTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Herramientas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esTools {
            get {
                return ResourceManager.GetString("esTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esView {
            get {
                return ResourceManager.GetString("esView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ventana과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esWindow {
            get {
                return ResourceManager.GetString("esWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string esXML {
            get {
                return ResourceManager.GetString("esXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frAction {
            get {
                return ResourceManager.GetString("frAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compléments과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frAddins {
            get {
                return ResourceManager.GetString("frAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Générer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frBuild {
            get {
                return ResourceManager.GetString("frBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagramme de classes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frClass_Diagram {
            get {
                return ResourceManager.GetString("frClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communauté과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frCommunity {
            get {
                return ResourceManager.GetString("frCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Données과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frData {
            get {
                return ResourceManager.GetString("frData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base de données과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frDatabase {
            get {
                return ResourceManager.GetString("frDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schéma de base de données과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frDatabase_Diagram {
            get {
                return ResourceManager.GetString("frDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Déboguer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frDebug {
            get {
                return ResourceManager.GetString("frDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schéma과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frDiagram {
            get {
                return ResourceManager.GetString("frDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frEdit {
            get {
                return ResourceManager.GetString("frEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fichier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frFile {
            get {
                return ResourceManager.GetString("frFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frFormat {
            get {
                return ResourceManager.GetString("frFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frames과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frFrames {
            get {
                return ResourceManager.GetString("frFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frHelp {
            get {
                return ResourceManager.GetString("frHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frImage {
            get {
                return ResourceManager.GetString("frImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disposition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frLayout {
            get {
                return ResourceManager.GetString("frLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macros과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frMacros {
            get {
                return ResourceManager.GetString("frMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frProject {
            get {
                return ResourceManager.GetString("frProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requête과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frQuery {
            get {
                return ResourceManager.GetString("frQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Concepteur de requêtes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frQuery_Designer {
            get {
                return ResourceManager.GetString("frQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refactoriser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frRefactor {
            get {
                return ResourceManager.GetString("frRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ressources과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frResources {
            get {
                return ResourceManager.GetString("frResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schéma과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frSchema {
            get {
                return ResourceManager.GetString("frSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Styles과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frStyles {
            get {
                return ResourceManager.GetString("frStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tableau과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frTable {
            get {
                return ResourceManager.GetString("frTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Concepteur de tables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frTable_Designer {
            get {
                return ResourceManager.GetString("frTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   équipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frTeam {
            get {
                return ResourceManager.GetString("frTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frTest {
            get {
                return ResourceManager.GetString("frTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outils과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frTools {
            get {
                return ResourceManager.GetString("frTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Affichage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frView {
            get {
                return ResourceManager.GetString("frView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fenêtre과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frWindow {
            get {
                return ResourceManager.GetString("frWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frXML {
            get {
                return ResourceManager.GetString("frXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Azione과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itAction {
            get {
                return ResourceManager.GetString("itAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Componenti aggiuntivi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itAddins {
            get {
                return ResourceManager.GetString("itAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itBuild {
            get {
                return ResourceManager.GetString("itBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagramma classi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itClass_Diagram {
            get {
                return ResourceManager.GetString("itClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comunità과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itCommunity {
            get {
                return ResourceManager.GetString("itCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dati과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itData {
            get {
                return ResourceManager.GetString("itData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itDatabase {
            get {
                return ResourceManager.GetString("itDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagramma database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itDatabase_Diagram {
            get {
                return ResourceManager.GetString("itDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itDebug {
            get {
                return ResourceManager.GetString("itDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagramma과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itDiagram {
            get {
                return ResourceManager.GetString("itDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modifica과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itEdit {
            get {
                return ResourceManager.GetString("itEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itFile {
            get {
                return ResourceManager.GetString("itFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formato과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itFormat {
            get {
                return ResourceManager.GetString("itFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itFrames {
            get {
                return ResourceManager.GetString("itFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itHelp {
            get {
                return ResourceManager.GetString("itHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Immagine과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itImage {
            get {
                return ResourceManager.GetString("itImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itLayout {
            get {
                return ResourceManager.GetString("itLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itMacros {
            get {
                return ResourceManager.GetString("itMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progetto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itProject {
            get {
                return ResourceManager.GetString("itProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itQuery {
            get {
                return ResourceManager.GetString("itQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progettazione query과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itQuery_Designer {
            get {
                return ResourceManager.GetString("itQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effettua refactoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itRefactor {
            get {
                return ResourceManager.GetString("itRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Risorse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itResources {
            get {
                return ResourceManager.GetString("itResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schema과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itSchema {
            get {
                return ResourceManager.GetString("itSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stili과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itStyles {
            get {
                return ResourceManager.GetString("itStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabella과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itTable {
            get {
                return ResourceManager.GetString("itTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progettazione tabelle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itTable_Designer {
            get {
                return ResourceManager.GetString("itTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itTeam {
            get {
                return ResourceManager.GetString("itTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prova과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itTest {
            get {
                return ResourceManager.GetString("itTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strumenti과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itTools {
            get {
                return ResourceManager.GetString("itTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visualizza과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itView {
            get {
                return ResourceManager.GetString("itView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finestra과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itWindow {
            get {
                return ResourceManager.GetString("itWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string itXML {
            get {
                return ResourceManager.GetString("itXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaAction {
            get {
                return ResourceManager.GetString("jaAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドイン과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaAddins {
            get {
                return ResourceManager.GetString("jaAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビルド과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaBuild {
            get {
                return ResourceManager.GetString("jaBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クラス ダイアグラム과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaClass_Diagram {
            get {
                return ResourceManager.GetString("jaClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コミュニティ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaCommunity {
            get {
                return ResourceManager.GetString("jaCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaData {
            get {
                return ResourceManager.GetString("jaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaDatabase {
            get {
                return ResourceManager.GetString("jaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース ダイアグラム과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaDatabase_Diagram {
            get {
                return ResourceManager.GetString("jaDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaDebug {
            get {
                return ResourceManager.GetString("jaDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダイアグラム과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaDiagram {
            get {
                return ResourceManager.GetString("jaDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaEdit {
            get {
                return ResourceManager.GetString("jaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaFile {
            get {
                return ResourceManager.GetString("jaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書式과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaFormat {
            get {
                return ResourceManager.GetString("jaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フレーム과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaFrames {
            get {
                return ResourceManager.GetString("jaFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaHelp {
            get {
                return ResourceManager.GetString("jaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イメージ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaImage {
            get {
                return ResourceManager.GetString("jaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaLayout {
            get {
                return ResourceManager.GetString("jaLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マクロ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaMacros {
            get {
                return ResourceManager.GetString("jaMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクト과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaProject {
            get {
                return ResourceManager.GetString("jaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaQuery {
            get {
                return ResourceManager.GetString("jaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ デザイナ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaQuery_Designer {
            get {
                return ResourceManager.GetString("jaQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リファクタ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaRefactor {
            get {
                return ResourceManager.GetString("jaRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソース과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaResources {
            get {
                return ResourceManager.GetString("jaResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキーマ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaSchema {
            get {
                return ResourceManager.GetString("jaSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタイル과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaStyles {
            get {
                return ResourceManager.GetString("jaStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaTable {
            get {
                return ResourceManager.GetString("jaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル デザイナ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaTable_Designer {
            get {
                return ResourceManager.GetString("jaTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チーム과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaTeam {
            get {
                return ResourceManager.GetString("jaTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaTest {
            get {
                return ResourceManager.GetString("jaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaTools {
            get {
                return ResourceManager.GetString("jaTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaView {
            get {
                return ResourceManager.GetString("jaView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaWindow {
            get {
                return ResourceManager.GetString("jaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jaXML {
            get {
                return ResourceManager.GetString("jaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koAction {
            get {
                return ResourceManager.GetString("koAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가 기능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koAddins {
            get {
                return ResourceManager.GetString("koAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빌드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koBuild {
            get {
                return ResourceManager.GetString("koBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클래스 다이어그램과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koClass_Diagram {
            get {
                return ResourceManager.GetString("koClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   커뮤니티과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koCommunity {
            get {
                return ResourceManager.GetString("koCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koData {
            get {
                return ResourceManager.GetString("koData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koDatabase {
            get {
                return ResourceManager.GetString("koDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스 다이어그램과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koDatabase_Diagram {
            get {
                return ResourceManager.GetString("koDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디버그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koDebug {
            get {
                return ResourceManager.GetString("koDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다이어그램과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koDiagram {
            get {
                return ResourceManager.GetString("koDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koEdit {
            get {
                return ResourceManager.GetString("koEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koFile {
            get {
                return ResourceManager.GetString("koFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서식과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koFormat {
            get {
                return ResourceManager.GetString("koFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프레임과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koFrames {
            get {
                return ResourceManager.GetString("koFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koHelp {
            get {
                return ResourceManager.GetString("koHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koImage {
            get {
                return ResourceManager.GetString("koImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   레이아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koLayout {
            get {
                return ResourceManager.GetString("koLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매크로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koMacros {
            get {
                return ResourceManager.GetString("koMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koProject {
            get {
                return ResourceManager.GetString("koProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿼리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koQuery {
            get {
                return ResourceManager.GetString("koQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿼리 디자이너과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koQuery_Designer {
            get {
                return ResourceManager.GetString("koQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리팩터링과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koRefactor {
            get {
                return ResourceManager.GetString("koRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리소스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koResources {
            get {
                return ResourceManager.GetString("koResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스키마과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koSchema {
            get {
                return ResourceManager.GetString("koSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스타일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koStyles {
            get {
                return ResourceManager.GetString("koStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koTable {
            get {
                return ResourceManager.GetString("koTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테이블 디자이너과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koTable_Designer {
            get {
                return ResourceManager.GetString("koTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   팀과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koTeam {
            get {
                return ResourceManager.GetString("koTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koTest {
            get {
                return ResourceManager.GetString("koTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koTools {
            get {
                return ResourceManager.GetString("koTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   뷰과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koView {
            get {
                return ResourceManager.GetString("koView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koWindow {
            get {
                return ResourceManager.GetString("koWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string koXML {
            get {
                return ResourceManager.GetString("koXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSAction {
            get {
                return ResourceManager.GetString("zh-CHSAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外接程序과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSAddins {
            get {
                return ResourceManager.GetString("zh-CHSAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSBuild {
            get {
                return ResourceManager.GetString("zh-CHSBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   类关系图과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社区과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSCommunity {
            get {
                return ResourceManager.GetString("zh-CHSCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSData {
            get {
                return ResourceManager.GetString("zh-CHSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据库과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSDatabase {
            get {
                return ResourceManager.GetString("zh-CHSDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据库关系图과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   调试과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSDebug {
            get {
                return ResourceManager.GetString("zh-CHSDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   关系图과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSDiagram {
            get {
                return ResourceManager.GetString("zh-CHSDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   编辑과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSEdit {
            get {
                return ResourceManager.GetString("zh-CHSEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文件과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSFile {
            get {
                return ResourceManager.GetString("zh-CHSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格式과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSFormat {
            get {
                return ResourceManager.GetString("zh-CHSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   框架과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSFrames {
            get {
                return ResourceManager.GetString("zh-CHSFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帮助과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSHelp {
            get {
                return ResourceManager.GetString("zh-CHSHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   图像과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSImage {
            get {
                return ResourceManager.GetString("zh-CHSImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   布局과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSLayout {
            get {
                return ResourceManager.GetString("zh-CHSLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   宏과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSMacros {
            get {
                return ResourceManager.GetString("zh-CHSMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   项目과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSProject {
            get {
                return ResourceManager.GetString("zh-CHSProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查询과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSQuery {
            get {
                return ResourceManager.GetString("zh-CHSQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查询设计器과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHSQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重构과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSRefactor {
            get {
                return ResourceManager.GetString("zh-CHSRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   资源과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSResources {
            get {
                return ResourceManager.GetString("zh-CHSResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   架构과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSSchema {
            get {
                return ResourceManager.GetString("zh-CHSSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   样式과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSStyles {
            get {
                return ResourceManager.GetString("zh-CHSStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSTable {
            get {
                return ResourceManager.GetString("zh-CHSTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表设计器과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHSTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工作组과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSTeam {
            get {
                return ResourceManager.GetString("zh-CHSTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   测试과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSTest {
            get {
                return ResourceManager.GetString("zh-CHSTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工具과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSTools {
            get {
                return ResourceManager.GetString("zh-CHSTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   视图과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSView {
            get {
                return ResourceManager.GetString("zh-CHSView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   窗口과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSWindow {
            get {
                return ResourceManager.GetString("zh-CHSWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHSXML {
            get {
                return ResourceManager.GetString("zh-CHSXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTAction {
            get {
                return ResourceManager.GetString("zh-CHTAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   增益集과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTAddins {
            get {
                return ResourceManager.GetString("zh-CHTAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建置과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTBuild {
            get {
                return ResourceManager.GetString("zh-CHTBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   類別圖表과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社群과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTCommunity {
            get {
                return ResourceManager.GetString("zh-CHTCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTData {
            get {
                return ResourceManager.GetString("zh-CHTData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料庫과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTDatabase {
            get {
                return ResourceManager.GetString("zh-CHTDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料庫圖表과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   偵錯과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTDebug {
            get {
                return ResourceManager.GetString("zh-CHTDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圖表과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTDiagram {
            get {
                return ResourceManager.GetString("zh-CHTDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編輯과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTEdit {
            get {
                return ResourceManager.GetString("zh-CHTEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檔案과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTFile {
            get {
                return ResourceManager.GetString("zh-CHTFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格式과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTFormat {
            get {
                return ResourceManager.GetString("zh-CHTFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   框架과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTFrames {
            get {
                return ResourceManager.GetString("zh-CHTFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   說明과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTHelp {
            get {
                return ResourceManager.GetString("zh-CHTHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   影像과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTImage {
            get {
                return ResourceManager.GetString("zh-CHTImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配置과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTLayout {
            get {
                return ResourceManager.GetString("zh-CHTLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   巨集과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTMacros {
            get {
                return ResourceManager.GetString("zh-CHTMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   專案과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTProject {
            get {
                return ResourceManager.GetString("zh-CHTProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTQuery {
            get {
                return ResourceManager.GetString("zh-CHTQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢設計工具과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHTQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重整과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTRefactor {
            get {
                return ResourceManager.GetString("zh-CHTRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資源과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTResources {
            get {
                return ResourceManager.GetString("zh-CHTResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結構描述과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTSchema {
            get {
                return ResourceManager.GetString("zh-CHTSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   樣式과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTStyles {
            get {
                return ResourceManager.GetString("zh-CHTStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料表과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTTable {
            get {
                return ResourceManager.GetString("zh-CHTTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   資料表設計工具과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHTTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小組과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTTeam {
            get {
                return ResourceManager.GetString("zh-CHTTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   測試과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTTest {
            get {
                return ResourceManager.GetString("zh-CHTTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工具과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTTools {
            get {
                return ResourceManager.GetString("zh-CHTTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   檢視과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTView {
            get {
                return ResourceManager.GetString("zh-CHTView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視窗과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTWindow {
            get {
                return ResourceManager.GetString("zh-CHTWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string zh_CHTXML {
            get {
                return ResourceManager.GetString("zh-CHTXML", resourceCulture);
            }
        }
    }
}
